### ISSUE TITLE
Grouping

### ISSUE THREAD

**Issue by twoxfh** [HaniAmmar/Qentem-Engine#1]
Thanks for making this template engine and opensourcing it.

Do you plan to support grouping of data? My json data is flat and would like to make it hierarchical. For example, years, months, days, topics, like a blog while using the the template tags to display data. 

Appreciate your feedback.

**Comment by HaniAmmar** [comment]
Hello,

First: you are welcome!
Second: could you please show me a basic template and some fake JSON data? Because I think it can do what you are asking. Also, how are you implementing this in your site? is it JS or PHP?

**Comment by HaniAmmar** [comment]
I think this is what you are asking: 
https://github.com/HaniAmmar/Qentem-Engine/blob/master/Examples/Template/Template13.cpp
forget about the code, just focus on the data and the temp

**Comment by twoxfh** [comment]
I am trying to pass in a flat json like:

```
[
  {
    "year": 2019,
    "quarter": "q1",
    "week": 1,
    "total": 100
  },
  {
    "year": 2019,
    "quarter": "q1",
    "week": 2,
    "total": 125
  },
  {
    "year": 2019,
    "quarter": "q2",
    "week": 1,
    "total": 200
  },
  {
    "year": 2019,
    "quarter": "q2",
    "week": 2,
    "total": 300
  },
  {
    "year": 2020,
    "quarter": "q1",
    "week": 1,
    "total": 400
  },
  {
    "year": 2020,
    "quarter": "q1",
    "week": 2,
    "total": 450
  }
]

```

And through the template define for each group on elements, year, quarter, week:

A template might look like
```
<forgroup set="year">
  <div>item[year]</div>
  <forgroup set="quater">
    <div>item[quater]</div>
    <forgroup set="week">
      <div>item[week]</div>
      <forgroup set="total">
        <div>item[total]</div>
      </forgroup>
     </forgroup>
   </forgroup>
</forgroup>
```

In memory the template engine is processing the flat json like a hierarchical one:
```
{
  "2019": {
    "q1": {
      "1": 100,
      "2": 125
    },
    "q2": {
      "1": 200,
      "2": 300
    }
  },
  "2020": {
    "q1": {
      "1": 400,
      "2": 450
    },
    "q2": {
      "1": 500
    }
  }
}
```

Does that make sense? I am using this in JS and ultimately through your JQen. I can do this in handlebars, however, your processor is speedy :)

**Comment by HaniAmmar** [comment]
Try this:

```html
<loop value="item">
<forgroup set="year">
  <div>item[year]</div>
  <forgroup set="quater">
    <div>item[quarter]</div>
    <forgroup set="week">
      <div>item[week]</div>
      <forgroup set="total">
        <div>item[total]</div>
      </forgroup>
     </forgroup>
   </forgroup>
</forgroup>
</loop>
```

I changed (quater) to (quarter)

**Comment by HaniAmmar** [comment]
there a file that will make you life much easier : https://github.com/HaniAmmar/JQen/blob/master/Examples/index.html

make folder inside your local-host server, say (jq). put inside it:
index.html
main.css
JQen.js
JQen.wasm

Access it through you browser.
![jq](https://user-images.githubusercontent.com/2579997/128611718-82223a46-0dd1-4e44-98fa-c34fd9ec4ea4.png)

**Comment by twoxfh** [comment]
![image](https://user-images.githubusercontent.com/30451770/128613793-09a9cc81-a76e-48d8-b6ae-d813a9041f52.png)

I get an error when trying to use it in Chrome and IE Chromium. Likely cause I am using https://raw.githack.com/HaniAmmar/JQen/master/Examples/index.html and Jqen is not built.in the directory. I built Jqen and uploaded it to a branch and it works. Let me know if you want a pull request.

**Comment by twoxfh** [comment]
For grouping data I was thinking of built in functionality like groupby[Link](https://github.com/shannonmoeller/handlebars-group-by)  in handlebars. I would want each json element printed once. I can understand creating a flat to tree structure is not within scope or maybe I am still missing something.

**Comment by HaniAmmar** [comment]
JQen.js and JQen.wasm are auto-generated using: https://emscripten.org/docs/getting_started/downloads.html
both of them  are not part of JQen. In any way, is it working for you now, on you PC?

For auto-grouping, I will check it, and get back to you on that.

thanks

**Comment by HaniAmmar** [comment]
Can you re-struct the JSON data? I mean, do have control over it (like change, modify)?
If that is yes, I can give you a basic template that does exactly what you want,
If not, then you need a JS function for regrouping the data: I can write that ... I think.

 I asked that because adding a new tag will take time, and also, I really do not want that for performance reasons. However, I think, once I find a way to implement grouping -without effecting the performance- I will code it in side the engine.

**Comment by twoxfh** [comment]
I am trying to keep my data structure and template configurable. I can preprocess using JavaScript but then it's not configurable or in one place. Another way might be  to implement functions over a loop. Loop distinct values for json key. Sort would also be really helpful.

This way you can loop json values for a key, make them distinct and then loop the distinct values. I'm not good with c++ but I will see if I can write something with a vector..

**Comment by HaniAmmar** [comment]
I get what you are saying: you what your data to be the same way you have configured it.

Alright, If you are not in a hurry, I'll try to work on something in the next few day, and because I'm in my final stage of publishing a book, I'm may start in the next two days or so.

I thank you for your though about writing a loop using std:vector, but the thing is: I'm not using **any** part of the C++ STL; for a few reasons, two of them are: customization and simplicity.

In any case, explain to me how you want (Grouping) to work, besides (sort). Me, I'm thinking about something like

```html
<loop ... groupby="value1-key" sort="ascend|descend">
    <div>some html with (groupby value1)</div>

    <grouped>
    -- some data and other values--
    </grouped>
<loop>
```

Let me know what you think.

**Comment by twoxfh** [comment]
I assume grouped can be looped? Sounds good but  my projects are hobby more important it's right for your project.

The more I think about this I wonder if I am suggesting the project go down a path it's not focused on. Maybe it should be combined with a json transformer which can be a project in it's self. I would hate to be the one who bloated the project 

Congrats on your book!

**Comment by HaniAmmar** [comment]
Yes, (grouped) is looped, and hobby are not, many hobby projects turned into professional projects like (Linux). This project is a hobby of mine, started to learn C++, at the end, I made a new hash-table. In addition to that, there are parts that I did not add yet: like escapeable values {vas:***}, which should escape HTML code and make it safe to be printed out to the browser.

I though about your suggestion, and it made sense to me after I remembered SQL has  grouping in it, and it has that because it’s **needed**. Besides, the code has already popped inside my head, and if I do not get it out, I will make me **crazy** :)

Implementing (grouped) will be to check once for (groupby), if it exist, the internal code will look for (grouped) one time, and will transform the template into two loops: main loop, and sub loop. It will take like 10-20 lines of code, at least that what I see in my head.

I'm not that good in picking names, especially in English. so if you think (grouped) is OK, I will go a head with it, unless you have better then that.

"Congrats on your book!"
Thank you!

**Comment by twoxfh** [comment]
Grouped is OK with me. On a side note, one thing I always try to do with HTML is create a char to color converter so I do not have to worry about colors and can blame the content; might be a useful feature for another issue. 

A Group test case may look something like:

Data:
```
[
  {
    "year": 2019,
    "quarter": "q1",
    "week": 1,
    "total": 100
  },
  {
    "year": 2019,
    "quarter": "q1",
    "week": 2,
    "total": 125
  },
  {
    "year": 2019,
    "quarter": "q2",
    "week": 1,
    "total": 200
  },
  {
    "year": 2019,
    "quarter": "q2",
    "week": 2,
    "total": 300
  },
  {
    "year": 2020,
    "quarter": "q1",
    "week": 1,
    "total": 400
  },
  {
    "year": 2020,
    "quarter": "q1",
    "week": 2,
    "total": 450
  }
]
```

Template:

```
<loop groupby="value1-key" sort="descend">
    <div>value1-key[year]</div>
    <grouped>
        <loop groupby="value1-key" sort="ascend">
            <div>value1-key[quarter]</div>
            <grouped>
                <loop groupby="value1-key" sort="ascend">
                    <div>value1-key[week]</div>
                    <grouped>
                        <div>value1-key[total]</div>
                    </grouped>
                </loop>        
            </grouped>
        </loop>
    </grouped>
</loop>
```

Expected Output:

```
<div>2020</div>
<div>q1</div>
<div>1</div>
<div>400</div>
<div>q1</div>
<div>2</div>
<div>450</div>
<div>2019</div>
<div>q1</div>
<div>1</div>
<div>100</div>
<div>q1</div>
<div>2</div>
<div>125</div>
<div>q2</div>
<div>1</div>
<div>200</div>
<div>q2</div>
<div>2</div>
<div>300</div>

```

**Comment by HaniAmmar** [comment]
I will take a few days because I never attended for (Template class) to manipulate JSON data, and so, I need to add (Value class) to it, and write a loop for grouping the data first, then another function for making an new content of the template, that adds a sub-loop.

**Comment by HaniAmmar** [comment]
Finally! after trees started growing out of my head, I made it working. I thought I would be rusty after 8-9 months, but nah. Anyway, let me break this down:

So, you say: you have this data, JSON data:
```json
[
    {
        "year": 2019,
        "quarter": "q1",
        "week": 1,
        "total": 100
    },
    {
        "year": 2019,
        "quarter": "q1",
        "week": 2,
        "total": 125
    },
    {
        "year": 2019,
        "quarter": "q2",
        "week": 1,
        "total": 200
    },
    {
        "year": 2019,
        "quarter": "q2",
        "week": 2,
        "total": 300
    },
    {
        "year": 2020,
        "quarter": "q1",
        "week": 1,
        "total": 400
    },
    {
        "year": 2020,
        "quarter": "q1",
        "week": 2,
        "total": 450
    }
]
``` 

and you want to print it out from a template. Let's take this a step by step. normally you need the following:
```html
<loop value="val1_">
<loop set="val1_" value="val2_">val2_
</loop>
</loop>
```
that is without the names of the names, with them, the number of loops can bee less by one:
```html
<loop value="val1_">
val1_[year]
val1_[quarter]
val1_[week]
val1_[total]
</loop>
```

Both will give:
```text
2019
q1
1
100


2019
q1
2
125


2019
q2
1
200


2019
q2
2
300


2020
q1
1
400


2020
q1
2
450
```

-----------------------------------------------------------------------------------

Now, if you want to group it by (year), you use the next template:
```html
<loop value="val1_" group="year" sort="descend">
Year (val1_): <loop set="val1_" value="val2_"><loop set="val2_" value="val3_"> val3_</loop></loop>
</loop>
```
or: 
```html
<loop value="val1_" group="year" sort="descend">
Year (val1_): <loop set="val1_" value="val2_">val2_[quarter] val2_[week] val2_[total] </loop>
</loop>
```

The data after grouping it by the (year) will look like:
```json
{
    "2020": [
        {
            "quarter": "q1",
            "week": 1,
            "total": 400
        },
        {
            "quarter": "q1",
            "week": 2,
            "total": 450
        }
    ],
    "2019": [
        {
            "quarter": "q1",
            "week": 1,
            "total": 100
        },
        {
            "quarter": "q1",
            "week": 2,
            "total": 125
        },
        {
            "quarter": "q2",
            "week": 1,
            "total": 200
        },
        {
            "quarter": "q2",
            "week": 2,
            "total": 300
        }
    ]
}
```

And the output is:
```txt
Year (2020):  q1 1 400 q1 2 450

Year (2019):  q1 1 100 q1 2 125 q2 1 200 q2 2 300
```
-----------------------------------------------------------------------------------
To group the grouped by (quarter), the data will end up looking like:
```json
{
    "2020": {
        "q1": [
            {
                "week": 1,
                "total": 400
            },
            {
                "week": 2,
                "total": 450
            }
        ]
    },
    "2019": {
        "q1": [
            {
                "week": 1,
                "total": 100
            },
            {
                "week": 2,
                "total": 125
            }
        ],
        "q2": [
            {
                "week": 1,
                "total": 200
            },
            {
                "week": 2,
                "total": 300
            }
        ]
    }
}
```

and the template that does that is:
```html
<loop value="val1_" group="year" sort="descend">
Year (val1_):<loop set="val1_" value="val2_" group="quarter" sort="ascend">
    Quarter(val2_):<loop set="val2_" value="val3_"> <loop set="val3_" value="val4_"> val4_</loop></loop></loop>
</loop>
```
or:
```html
<loop value="val1_" group="year" sort="descend">
Year (val1_):<loop set="val1_" value="val2_" group="quarter" sort="ascend">
    Quarter(val2_):<loop set="val2_" value="val3_"> val3_[week] val3_[total]</loop></loop>
</loop>
```

Output:
```txt
Year (2020):
    Quarter(q1):  1 400  2 450

Year (2019):
    Quarter(q1):  1 100  2 125
    Quarter(q2):  1 200  2 300
```

---------------------
Now for grouping by the (week):
```html
<loop value="val1_" group="year" sort="descend">
Year (val1_):<loop set="val1_" value="val2_" group="quarter" sort="ascend">
    Quarter(val2_):<loop set="val2_" value="val3_" group="week" sort="ascend">
        Week(val3_):<loop set="val3_" value="val4_"><loop set="val4_" value="val5_"> val5_</loop></loop></loop>
</loop>
</loop>
```

or:
```html
<loop value="val1_" group="year" sort="descend">
Year (val1_):<loop set="val1_" value="val2_" group="quarter" sort="ascend">
    Quarter(val2_):<loop set="val2_" value="val3_" group="week" sort="ascend">
        Week(val3_): <loop set="val3_" value="val4_">val4_[total]</loop></loop>
</loop>
</loop>
```

Output:
```txt
Year (2020):
    Quarter(q1):
        Week(1): 400
        Week(2): 450


Year (2019):
    Quarter(q1):
        Week(1): 100
        Week(2): 125

    Quarter(q2):
        Week(1): 200
        Week(2): 300
```

The JSON data is:
```json
{
    "2020": {
        "q1": {
            "1": [
                {
                    "total": 400
                }
            ],
            "2": [
                {
                    "total": 450
                }
            ]
        }
    },
    "2019": {
        "q1": {
            "1": [
                {
                    "total": 100
                }
            ],
            "2": [
                {
                    "total": 125
                }
            ]
        },
        "q2": {
            "1": [
                {
                    "total": 200
                }
            ],
            "2": [
                {
                    "total": 300
                }
            ]
        }
    }
}
```

I hope you are noticing that with each (group) you add a (loop).


-------------------
I updated JQen to 1.5: https://github.com/HaniAmmar/JQen/releases/
try it and let me know.

Note:
The changes did not effect the performance at a noticeable level: 0.005 or something, but with other changes, it became faster than before. Also, I did not add (grouped) tag, because after thinking, it's not needed. (simplicity is better -in my opinion).

If you want to try grouping JSON using this engine, I made C++ file for that:
```cpp
#include "JSON.hpp"

#include <fstream>
#include <iostream>

///////////////////////////////////////////////////

using Value  = Qentem::Value<char>;
using String = Qentem::String<char>;
using Qentem::SizeT;

///////////////////////////////////////////////////
String ReadFile(const char *path);
///////////////////////////////////////////////////

int main() {
    const String year    = String("year");
    const String quarter = String("quarter");
    const String week    = String("week");
    const String data    = ReadFile("./Notes/temp7.json");

    Value tmp;
    Value tmp2;
    Value value = Qentem::JSON::Parse(data.First(), data.Length());

    value.GroupBy(tmp, year.First(), year.Length());
    value = static_cast<Value &&>(tmp);
    value.Sort(false);

    for (SizeT i = 0; i < value.Size(); i++) {
        value[i].GroupBy(tmp, quarter.First(), quarter.Length());
        tmp.Sort();

        for (SizeT j = 0; j < tmp.Size(); j++) {
            tmp[j].GroupBy(tmp2, week.First(), week.Length());
            tmp2.Sort();
            tmp[j] = static_cast<Value &&>(tmp2);
        }

        value[i] = static_cast<Value &&>(tmp);
    }

    std::cout << value.Stringify() << '\n';
}

///////////////////////////////////////////////////

QENTEM_MAYBE_UNUSED String ReadFile(const char *path) {
    std::ifstream file(path, std::ios::ate | std::ios::out);

    if (file.is_open()) {
        const std::streampos size = file.tellg();
        file.seekg(0, std::ios::beg);

        auto const len = static_cast<SizeT>(size);
        char *     str = Qentem::Memory::Allocate<char>(len + 1);

        file.read(str, size);
        file.close();

        return String(str, len);
    }

    return String("");
}
```

to compile: 
```txt
g++ ./group.cpp -std=c++11 -I ./Include -o ./o.bin
```

**Comment by twoxfh** [comment]
This is great, thank you!. I compiled your changes and put them in my example branch and linked it here: 
https://rawcdn.githack.com/twoxfh/JQen/6bb2b95ceb2a3b9d6a7299e0479e1831cb427b70/Examples/index.html. I have not run performance yet, but things are looking good.

**Comment by HaniAmmar** [comment]
You are welcome!

Please note that (sort) is not limited to (grouped values); it can be applied to any array or object. Also, I added auto-escape and a new tag ({raw:...}) for printing pure data with (< > & ' " ) HTML special chars. (still working on it).

If you would like me to add another feature to QLib, let me know :)

Note I may make a repo for githack.com (nice one that one), and you are welcome to help with JQen tool. (like css and its colors).

**Comment by HaniAmmar** [comment]
I have updated the examples in my comment: https://github.com/HaniAmmar/Qentem-Engine/issues/1#issuecomment-898655006
and the new ones has one less loop, and they should be faster.
