### ISSUE TITLE
String cannot be used as template on arduino ide (minor issue)

### ISSUE THREAD

**Issue by rjjrbatarao** [HaniAmmar/Qentem-Engine#3]
Sorry for making this arduino platform specific .This might be an issue for some but not for me since i prefer using char buffers other than arduino String.

**Comment by HaniAmmar** [comment]
That's fine, send me the error and I will look into it, also try the new changes that I made, it might fix it.

**Comment by HaniAmmar** [comment]
I think I know the issue, try this:

```cpp
using CString = Qentem::String<char>;

CString str = "any"; // or
CString str{"any"};
```

**Comment by rjjrbatarao** [comment]
i was trying to make a string like this based on the example test files
```c++
String<char> str; 
```c++
ok maybe i try to use it Qentem::String<char> str; should do the trick thank you

**Comment by HaniAmmar** [comment]
in OOP languages, anything in a library should be in a namespace unique to that library, unless it's an extension, or it will be a major engineering issue, and the code will not compile because of conflicts (structs with the same name).
