### ISSUE TITLE
Engine parsing exception for decimals less than 1

### ISSUE THREAD

**Issue by LiujhDev** [HaniAmmar/Qentem-Engine#8]
int main() {
    Value<char> value;

    value["name"]       = "Qentem";
    value["version"]    = 0.14;
    const char *content = R"({var:name}, {var:version})";

    StringStream<char> stream;

    Template::Render(content, value, stream);
    std::cout << stream << '\n';

    /*
        Output:
            Qentem, 140
    */
}

**Comment by HaniAmmar** [comment]
Fixed f6679c8271ab6df58ca40560d44336c9bce9950c

Thank you for reporting this.
